webdriver {
    driver = chrome
    autodownload = true
    base.url = "http://localhost:3000"
    timeouts {
        implicitly_wait = 15000
        wait_for_timeout = 15000
    }
}

headless.mode = false

serenity {
    project.name = "AUTO_FRONT_SCREENPLAY"
    take.screenshots = FOR_FAILURES
}

environments {
    default {
        base.url = "http://localhost:3000"
        login.path = "/login"
        register.path = "/register"
    }
}

test.credentials {
    email = "testuser@auto.com"
    password = "Password123!"
    name = "Test User"
}
