webdriver {
    driver = chrome
    autodownload = true
    base.url = "http://localhost:3000"
    timeouts {
        implicitly_wait = 20000
        wait_for_timeout = 20000
    }
}

headless.mode = false

serenity {
    project.name = "AUTO_FRONT_SCREENPLAY"
    take.screenshots = FOR_FAILURES
}
